services:
  php:
    build: .
    container_name: praktikum_php
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - praktikum_network
    expose:
      - "9000"

  nginx:
    image: nginx:stable
    container_name: praktikum_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - praktikum_network

  mysql:
    image: mysql:8
    container_name: praktikum_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: praktikum_rpl
      MYSQL_USER: rafli
      MYSQL_PASSWORD: rafli123
    ports:
      - "3307:3306"
    networks:
      - praktikum_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: praktikum_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - praktikum_network

networks:
  praktikum_network:
    driver: bridge
